name: titiknol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  form_builder_validators: ^11.0.0
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0
  flutter_local_notifications: ^17.2.2
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.4.1
  flutter_launcher_icons: ^0.13.1  
  get: ^4.6.6
  http: ^1.2.2
  mobile_scanner: ^3.0.0    # cek versi terbaru di pub.dev saat implementasi
  package_info_plus: ^4.0.0
  permission_handler: ^10.0.0
  qr_flutter: ^4.1.0
  recase: ^4.1.0
  shared_preferences: ^2.3.2
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - .env.dev
    - .env.prod

  fonts:
  - family: Robotox
    fonts:
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Bold.ttf
        weight: 700
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png" 